version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      - 'POSTGRES_DB=insurance'
      - 'POSTGRES_PASSWORD=insurance'
      - 'POSTGRES_USER=insurance'
    ports:
      - '5432:5432'

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.6
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.6
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  mockserver:
    image: mockserver/mockserver:5.15.0
    ports:
      - "1080:1080"
    volumes:
      - ./catalog-ms-mockserver/catalog-ms-mock-data.json:/config/init_expectations.json
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/init_expectations.json
      MOCKSERVER_LOG_LEVEL: WARN

  insurance-policy-ms-mock:
    build: ./insurance-policy-ms-mock
    depends_on:
      - kafka
    environment:
      - KAFKAJS_NO_PARTITIONER_WARNING=1
      - ENABLED=false
